export enum FlowStatus {
  INVITED = "INVITED",
  EXPIRED = "EXPIRED",
  CONSENT_ACCEPTED = "CONSENT_ACCEPTED",
  CONSENT_REFUSED = "CONSENT_REFUSED",
  BANK_CONSENT_ACCEPTED = "BANK_CONSENT_ACCEPTED",
  BANK_CONSENT_REFUSED = "BANK_CONSENT_REFUSED",
  REPORT_GENERATED = "REPORT_GENERATED",
  REPORT_SAVED = "REPORT_SAVED",
  REPORT_REFUSED = "REPORT_REFUSED",
  BANK_ERROR = "BANK_ERROR",
}
