export enum InvitationStatus {
  INVITED = "INVITED",
  REFUSED_BANK_CONSENT = "REFUSED_BANK_CONSENT",
  ERROR_BANK = "ERROR_BANK",
  REFUSED = "REFUSED",
  REPORT_SHARED = "REPORT_SHARED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  REPORT_SHARING_REFUSED = "REPORT_SHARING_REFUSED",
  ERROR = "ERROR",
}
