export enum CreditScoreAggregations {
  LOANS = "LOANS",
  EQUITY_FINANCING = "EQUITY_FINANCING",
  REVENUE = "REVENUE",
  TAX_RETURNS = "TAX_RETURNS",
  OTHER_INCOME = "OTHER_INCOME",
  INVESTMENTS = "INVESTMENTS",
  FOOD_AND_DRINKS = "FOOD_AND_DRINKS",
  VEHICLE_AND_DRIVING_EXPENSES = "VEHICLE_AND_DRIVING_EXPENSES",
  RENT_AND_FACILITIES = "RENT_AND_FACILITIES",
  TRAVEL_EXPENSES = "TRAVEL_EXPENSES",
  MARKETING_AND_PROMOTION = "MARKETING_AND_PROMOTION",
  OTHER_OPERATING_COSTS = "OTHER_OPERATING_COSTS",
  UTILITIES = "UTILITIES",
  COLLECTION_COSTS = "COLLECTION_COSTS",
  SALARIES = "SALARIES",
  PENSION_PAYMENTS = "PENSION_PAYMENTS",
  CORPORATE_SAVINGS_DEPOSITS = "CORPORATE_SAVINGS_DEPOSITS",
  EQUITY_WITHDRAWAL = "EQUITY_WITHDRAWAL",
  SALES_TAX = "SALES_TAX",
  PAYROLL_TAX = "PAYROLL_TAX",
  CORPORATE_INCOME_TAX = "CORPORATE_INCOME_TAX",
  UNSPECIFIED_TAX = "UNSPECIFIED_TAX",
  OTHER_EXPENSES = "OTHER_EXPENSES",
}

export type CreditScoreAggregationsType = typeof CreditScoreAggregations;

export type CreditScoreAggregationsTypeString =
  keyof CreditScoreAggregationsType;
