POST {{baseUrl}}/yts-credit-scoring-app/api/admin/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}


###

POST {{baseUrl}}/yts-credit-scoring-app/api/sites/connect/33aca8b9-281a-4259-8492-1b37706af6db
hash:W6ZfX5i2sBK_z7akH6x4TK1dgbqNORkRu0CpQgslSx37k3mny6-nhrdp3Nfc
x-real-ip:192.168.0.1


###


GET {{baseUrl}}/yts-credit-scoring-app/api/admin/logout

###
